language: python
cache: pip
python:
  - '3.7'
  - '3.8'
  - '3.9'
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pylama wapi2nsconf
  - poetry run isort --check wapi2nsconf
  - poetry run black --check wapi2nsconf
  - poetry run wapi2nsconf --check --conf wapi2nsconf-example.yaml
notifications:
  email: false
